name: Build and run Maestro tests (Flutter Android)

on:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current (test) repo
        uses: actions/checkout@v3
      - name: Clone Flutter app repo
        run: |
          git clone https://github.com/Buenro/hotel-search.git flutter_app
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - name: Create .env file
        run: |
          echo "SERPAPI_API_KEY=${{ secrets.SERPAPI_API_KEY }}" > flutter_app/.env
      - name: Generate env.g.dart
        run: |
          cd flutter_app
          flutter pub get
          flutter pub run build_runner build --delete-conflicting-outputs
      - name: Build Flutter debug APK
        run: |
          cd flutter_app
          flutter build apk --debug
      - uses: mobile-dev-inc/action-maestro-cloud@v1
        with:
          api-key: ${{ secrets.MAESTRO_API_KEY }}
          project-id: org_01jx0rcw50e6ca7c88r3wxpq70
          app-file: flutter_app/build/app/outputs/flutter-apk/app-debug.apk
      - name: Run Maestro Tests
        run: |
          maestro test .maestro/flows/search.yaml --debug-output ./output
